import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { processContent } from '@dawn/content-pipeline';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '../../..');
const contentRoot = join(repoRoot, 'content');
const outDir = join(repoRoot, 'packages/game-data/src/generated');

const result = processContent(contentRoot);

if (result.errors.length > 0) {
  console.error('Content pipeline errors:');
  for (const err of result.errors) {
    console.error(`  [${err.file}] ${err.message}`);
  }
  process.exit(1);
}

if (result.warnings.length > 0) {
  console.warn('Content pipeline warnings:');
  for (const warn of result.warnings) {
    console.warn(`  [${warn.file}] ${warn.message}`);
  }
}

mkdirSync(outDir, { recursive: true });

function serializeConst(name: string, data: unknown): string {
  return `export const ${name} = ${JSON.stringify(data, null, 2)} as const;\n`;
}

const contentTs = `// AUTO-GENERATED by content:codegen — do not edit
import type { EnemyDefinition, SkillDefinition, StatusDefinition } from '@dawn/types';

${serializeConst('generatedSkills', result.skills).replace('as const;', 'as const satisfies readonly SkillDefinition[];')}
${serializeConst('generatedStatuses', result.statuses).replace('as const;', 'as const satisfies readonly StatusDefinition[];')}
${serializeConst('generatedEnemies', result.enemies).replace('as const;', 'as const satisfies readonly EnemyDefinition[];')}

export const skills: SkillDefinition[] = [...generatedSkills];
export const statuses: StatusDefinition[] = [...generatedStatuses];
export const enemies: EnemyDefinition[] = [...generatedEnemies];
`;

const referencesTs = `// AUTO-GENERATED by content:codegen — do not edit
export const contentReferences = ${JSON.stringify(result.references, null, 2)} as const;

export type ContentReferences = typeof contentReferences;
`;

writeFileSync(join(outDir, 'content.ts'), contentTs);
writeFileSync(join(outDir, 'references.ts'), referencesTs);

console.log(
  `Generated ${result.skills.length} skills, ${result.statuses.length} statuses, ${result.enemies.length} enemies`,
);
