import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { processContent } from '@dawn/content-pipeline';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '../../..');
const contentRoot = join(repoRoot, 'content');
const outDir = join(repoRoot, 'packages/game-data/src/generated');

const result = processContent(contentRoot);

if (result.errors.length > 0) {
  console.error('Content pipeline errors:');
  for (const err of result.errors) {
    console.error(`  [${err.file}] ${err.message}`);
  }
  process.exit(1);
}

if (result.warnings.length > 0) {
  console.warn('Content pipeline warnings:');
  for (const warn of result.warnings) {
    console.warn(`  [${warn.file}] ${warn.message}`);
  }
}

mkdirSync(outDir, { recursive: true });

function serializeConst(name: string, data: unknown): string {
  return `export const ${name} = ${JSON.stringify(data, null, 2)} as const;\n`;
}

const statIds = result.combatStats.stats.map((s) => s.id);
const combatStatIdUnion = statIds.map((id) => `  | '${id}'`).join('\n');

const combatStatsTs = `// AUTO-GENERATED by content:codegen — do not edit
import type { CombatStatsConfig } from '@dawn/types';

export type CombatStatId =
${combatStatIdUnion};

export const COMBAT_STAT_IDS: readonly CombatStatId[] = ${JSON.stringify(statIds)} as const;

export const combatStatsConfig: CombatStatsConfig = ${JSON.stringify(result.combatStats, null, 2)};
`;

const contentTs = `// AUTO-GENERATED by content:codegen — do not edit
import type { EnemyDefinition, SkillDefinition, TagDefinition } from '@dawn/types';

${serializeConst('generatedSkills', result.skills).replace('as const;', 'as const satisfies readonly SkillDefinition[];')}
${serializeConst('generatedTags', result.tags).replace('as const;', 'as const satisfies readonly TagDefinition[];')}
${serializeConst('generatedEnemies', result.enemies).replace('as const;', 'as const satisfies readonly EnemyDefinition[];')}

export const skills: SkillDefinition[] = [...generatedSkills];
export const tags: TagDefinition[] = [...generatedTags];
export const enemies: EnemyDefinition[] = [...generatedEnemies];

/** @deprecated Use tags */
export const statuses: TagDefinition[] = tags;
`;

const referencesTs = `// AUTO-GENERATED by content:codegen — do not edit
export const contentReferences = ${JSON.stringify(result.references, null, 2)} as const;

export type ContentReferences = typeof contentReferences;
`;

writeFileSync(join(outDir, 'combat-stats.ts'), combatStatsTs);
writeFileSync(join(outDir, 'content.ts'), contentTs);
writeFileSync(join(outDir, 'references.ts'), referencesTs);

console.log(
  `Generated ${result.skills.length} skills, ${result.tags.length} tags, ${result.enemies.length} enemies, ${statIds.length} combat stats`,
);
